/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Contenedor;

import javax.swing.JOptionPane;

/**
 *
 * @author josue
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPosicion = new javax.swing.JTextField();
        BtnFibonacci = new javax.swing.JButton();
        Memoized = new javax.swing.JButton();
        buttton_up = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BtnFibonacci.setText("Fibonacci Normal");
        BtnFibonacci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFibonacciActionPerformed(evt);
            }
        });

        Memoized.setText("Fibonacci Memorizacion");
        Memoized.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MemoizedActionPerformed(evt);
            }
        });

        buttton_up.setText("De abajo hacia arriba");
        buttton_up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttton_upActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(BtnFibonacci)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(Memoized, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(txtPosicion, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(buttton_up)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(txtPosicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnFibonacci)
                    .addComponent(Memoized))
                .addGap(49, 49, 49)
                .addComponent(buttton_up)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnFibonacciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFibonacciActionPerformed
        pila = new java.util.Stack<>();

        int posicion = Integer.parseInt(txtPosicion.getText());
        int valor = Fibonacci(posicion);
        JOptionPane.showMessageDialog(this, "El Fibonacci de "
            +posicion+" es "+valor);
    }//GEN-LAST:event_BtnFibonacciActionPerformed

    private void MemoizedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MemoizedActionPerformed
        // TODO add your handling code here:
        pila = new java.util.Stack<>();
        int posicion = Integer.parseInt(txtPosicion.getText());
        int valor = fibonacciMemoized(posicion,null);

        JOptionPane.showMessageDialog(this, "El Fibonacci de "
            +posicion+" es "+valor);
    }//GEN-LAST:event_MemoizedActionPerformed

    private void buttton_upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttton_upActionPerformed
        // TODO add your handling code here:
        pila = new java.util.Stack<>();
        int posicion = Integer.parseInt(txtPosicion.getText());
        int valor = fib_bottom_up(posicion,null);

        JOptionPane.showMessageDialog(this, "El Fibonacci de "
            +posicion+" es "+valor);
    }//GEN-LAST:event_buttton_upActionPerformed
 //Funcion Normal
    private java.util.Stack<Integer> pila = new java.util.Stack();
    private int Fibonacci(int posicion){
        posicion = java.lang.Math.abs(posicion);
        if(posicion < 2) return posicion;
        else{
            int respuesta = Fibonacci(posicion - 1) + Fibonacci(posicion - 2);
            pila.push(respuesta);
            return respuesta;
        }
        
    }

   int result;
   //Funcion de momoized 
    private int fibonacciMemoized(int posicion, int [] mem ){
       int[]memo= new int[posicion+1];
       
  if(memo[(int)posicion]!=0){
   return memo[(int)posicion];
  
    }else if(posicion ==1 || posicion==2){
    result = 1;
    } else {
    result = fibonacciMemoized(posicion-1,mem) + fibonacciMemoized(posicion-2,mem);
    memo[posicion]=result;
    }
    return result;
   
    }

      //Funcion de abajo hacia arriba 
    private int fib_bottom_up(int posicion,int []m){
       int[]bottom_up= new int[posicion+1];
          posicion = java.lang.Math.abs(posicion);
       if(posicion ==1 || posicion==2) return 1;
       {
   bottom_up[posicion]= bottom_up[(int)posicion]=0 * (posicion + 1);
    bottom_up[1] =1;
    bottom_up[2] =2;
    
       }
    for(int i = 2; i<=(posicion); i++){
    bottom_up[i] = bottom_up[i - 1] + bottom_up[i - 2]; 
     }
        return bottom_up[posicion];
     
    } 
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnFibonacci;
    private javax.swing.JButton Memoized;
    private javax.swing.JButton buttton_up;
    private javax.swing.JTextField txtPosicion;
    // End of variables declaration//GEN-END:variables
}
